# Generated by Django 5.2 on 2026-03-15 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='TortugaTur', max_length=150)),
                ('ruc', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Configuracion de Empresa',
                'verbose_name_plural': 'Configuracion de Empresa',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='agencia_contacto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='agencia_correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='agencia_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reserva',
            name='agencia_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reserva',
            name='alerta_24h_agencia_enviada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='alerta_7d_agencia_enviada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='archivo_agencia',
            field=models.FileField(blank=True, null=True, upload_to='agencia_vouchers/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_agencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='gestionada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_gestionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_turno_agencia',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_turno_libre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='limite_pago_agencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado_agencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones_agencia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('general', 'Reserva General'), ('agencia', 'Reserva de Agencia')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='salidatour',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salidatour',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: Medio día (4 horas)', max_length=100, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='salidatour',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='descuento_ninos_activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, los ninos pagan tarifa de adulto.', verbose_name='Aplicar descuento a ninos'),
        ),
        migrations.AddField(
            model_name='tour',
            name='descuento_ninos_agencia_activo',
            field=models.BooleanField(default=False, help_text='Control independiente para proceso de agencias.', verbose_name='Aplicar descuento ninos (agencias)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 4 horas, Medio día, etc.', max_length=100, null=True, verbose_name='Duración del tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hora_turno_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Turno 1'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hora_turno_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Turno 2'),
        ),
        migrations.AddField(
            model_name='tour',
            name='lemonsqueezy_variant_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_nino',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tour',
            name='visible_para_agencias',
            field=models.BooleanField(default=True, help_text='Si se desactiva, este tour no aparecera para cuentas de agencia.', verbose_name='Visible para agencias'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('solicitud_agencia', 'Solicitud Agencia'), ('cotizada_agencia', 'Cotizada Agencia'), ('confirmada_agencia', 'Confirmada Agencia'), ('pagada_parcial_agencia', 'Pagada Parcial Agencia'), ('pagada_total_agencia', 'Pagada Total Agencia'), ('rechazada_agencia', 'Rechazada Agencia'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('bloqueada_por_agencia', 'Bloqueada por Agencia')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='salidatour',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='salidatour',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='Sube una foto local (desde tu PC)', null=True, upload_to='galeria_tours/')),
                ('imagen_url', models.URLField(blank=True, help_text='O pega el enlace de Drive/Photos/Internet', max_length=500, null=True)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('lemonsqueezy', 'Lemon Squeezy'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=20)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('checkout_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.reserva')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='perfiles/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, default='', max_length=20)),
                ('force_password_change', models.BooleanField(default=False)),
                ('is_agencia', models.BooleanField(default=False, help_text='Si se activa, el usuario podrá bloquear reservas por 15 días', verbose_name='Es agencia de tours')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
