# Generated by Django 5.2 on 2026-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reserva_cotizacion_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='destinos/'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Imagen (URL)'),
        ),
    ]
