# Generated by Django 5.2 on 2026-04-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_destino_imagen_alter_destino_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='contacto_whatsapp_directo',
            field=models.BooleanField(default=False, help_text='Si se activa, este tour no se reserva desde la web y mostrara un boton para contactar por WhatsApp.', verbose_name='Contacto por WhatsApp'),
        ),
        migrations.AddField(
            model_name='tour',
            name='mensaje_contacto_whatsapp',
            field=models.TextField(blank=True, default='', help_text='Texto corto para invitar al cliente a escribir por WhatsApp. Si se deja vacio, se usara un mensaje por defecto.', verbose_name='Mensaje de contacto por WhatsApp'),
        ),
    ]
