from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

# URLs de TortugaTur
urlpatterns = [
    path("", views.home, name="home"),
    path("tours/", views.tours, name="tours"),
    path("buscar/", views.lista_tours, name="lista_tours"),
    path("tours/<int:pk>/", views.tour_detalle, name="tour_detalle"),
    path("tours/<int:pk>/resena/", views.crear_resena, name="crear_resena"),
    path('nosotros/', views.nosotros, name='nosotros'),
    path('contacto/', views.contacto, name='contacto'),
    path('terminos-y-condiciones/', views.terminos, name='terminos'),
    path('preguntas-frecuentes/', views.faq, name='faq'),

    path("panel/", views.panel_inicio, name="panel_admin"),
    path("panel/reservas/", views.admin_reservas, name="admin_reservas"),
    path("panel/reservas/estado/json/", views.admin_reservas_estado_json, name="admin_reservas_estado_json"),
    path("panel/agencias-sin-pago/", views.admin_agencias_sin_pago, name="admin_agencias_sin_pago"),
    path("panel/reservas/<int:reserva_id>/estado/", views.cambiar_estado_reserva, name="cambiar_estado_reserva"),
    path("panel/reservas/<int:reserva_id>/solicitud-agencia/", views.gestionar_solicitud_agencia, name="gestionar_solicitud_agencia"),
    path("panel/reservas/<int:reserva_id>/registrar-pago-agencia/", views.registrar_pago_agencia, name="registrar_pago_agencia"),
    path("panel/reservas/<int:reserva_id>/registrar-monto-agencia/", views.registrar_monto_agencia, name="registrar_monto_agencia"),
    path("panel/reservas/<int:reserva_id>/registrar-monto-interno/", views.registrar_monto_reserva_interna, name="registrar_monto_reserva_interna"),
    path("panel/reservas/<int:reserva_id>/actualizar-telefono-interno/", views.actualizar_telefono_reserva_interna, name="actualizar_telefono_reserva_interna"),
    path("agencia/factura-mensual/pdf/", views.factura_agencia_mensual_pdf, name="factura_agencia_mensual_pdf"),
    path("panel/reservas/<int:reserva_id>/eliminar/", views.eliminar_reserva, name="eliminar_reserva"),
    path("panel/salidas/", views.admin_salidas, name="admin_salidas"),
    path("panel/salidas/<int:salida_id>/editar/", views.editar_salida, name="editar_salida"),
    path("panel/salidas/<int:salida_id>/eliminar/", views.eliminar_salida, name="eliminar_salida"),
    path("panel/salidas/limpiar/", views.limpiar_salidas_vacias, name="limpiar_salidas_vacias"),
    path("panel/salidas/nueva/", views.crear_salida, name="crear_salida"),
    path("panel/destinos/", views.destinos, name="destinos"),
    path("panel/destinos/editar/<int:pk>/", views.editar_destino, name="editar_destino"),
    path("panel/destinos/eliminar/<int:pk>/", views.eliminar_destino, name="eliminar_destino"),
    path("panel/tours/", views.admin_tours, name="admin_tours"),
    path("panel/tours/editar/<int:pk>/", views.editar_tour, name="editar_tour"),
    path("panel/tours/eliminar/<int:pk>/", views.eliminar_tour, name="eliminar_tour"),
    path("panel/galeria/", views.panel_galeria, name="panel_galeria"),
    path("panel/galeria/eliminar-multiple/", views.eliminar_galeria_multiple, name="eliminar_galeria_multiple"),
    path("panel/galeria/eliminar/<int:pk>/", views.eliminar_galeria, name="eliminar_galeria"),
    path("panel/empresa/", views.empresa_config, name="empresa_config"),
    path("panel/perfil/", views.perfil_admin, name="perfil_admin"),
    path("panel/agencias/", views.admin_agencias, name="admin_agencias"),
    path("panel/agencias/nueva/", views.crear_agencia, name="crear_agencia"),
    path("panel/agencias/<int:user_id>/reset-password/", views.reset_agencia_password, name="reset_agencia_password"),
    path("panel/agencias/<int:user_id>/toggle/", views.toggle_agencia, name="toggle_agencia"),
    path("panel/agencias/<int:user_id>/eliminar/", views.eliminar_agencia, name="eliminar_agencia"),
    path("panel/secretarias/", views.admin_secretarias, name="admin_secretarias"),
    path("panel/secretaria/", views.panel_secretaria, name="panel_secretaria"),
    path("panel/secretaria/reservar/", views.secretaria_reservar, name="secretaria_reservar"),
    path("panel/secretarias/<int:user_id>/toggle/", views.toggle_secretaria_estado, name="toggle_secretaria_estado"),
    path("panel/secretarias/<int:user_id>/eliminar/", views.eliminar_secretaria, name="eliminar_secretaria"),
    path("panel/secretarias/<int:user_id>/reset-password/", views.reset_secretaria_password, name="reset_secretaria_password"),
    path("panel/actividad/secretarias-fragment/", views.panel_actividad_secretarias_fragment, name="panel_actividad_secretarias_fragment"),
    path("panel/actividad/pdf/", views.descargar_actividad_dia_pdf, name="descargar_actividad_dia_pdf"),
    path("panel/reportes/pdf/rango/", views.descargar_reporte_rango_pdf, name="descargar_reporte_rango_pdf"),
    path("panel/actividad/", views.panel_actividad, name="panel_actividad"),
    path("panel/notificaciones/json/", views.panel_notificaciones_json, name="panel_notificaciones_json"),
    path("panel/secretaria/notificaciones/json/", views.panel_notificaciones_secretaria_json, name="panel_notificaciones_secretaria_json"),

    path('registro/', views.registro, name='registro'),
    path('login/', views.vista_login, name='login'),
    path('logout/', views.vista_logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    path('mis-reservas/', views.mis_reservas, name='mis_reservas'),
    path('mis-reservas/<int:reserva_id>/cancelar-agencia/', views.cancelar_reserva_agencia, name='cancelar_reserva_agencia'),
    
    path('ticket/<int:reserva_id>/', views.ticket_reserva, name='ticket_reserva'),
    path('ticket/<int:reserva_id>/pdf/', views.ver_ticket_pdf, name='ver_ticket_pdf'),
    
    path('checkout/', views.checkout_redirect, name='checkout'),
    path('checkout/<int:reserva_id>/', views.checkout_pago, name='checkout_reserva'),
    path('checkout/<int:reserva_id>/cancelar/', views.cancelar_reserva_checkout, name='cancelar_reserva_checkout'),
    path('checkout/<int:reserva_id>/efectivo/', views.procesar_pago_efectivo, name='procesar_pago_efectivo'),
    path('pagos/lemonsqueezy/<int:reserva_id>/checkout/', views.create_lemonsqueezy_checkout, name='create_lemonsqueezy_checkout'),
    path('pagos/paypal/<int:reserva_id>/order/', views.create_paypal_order, name='create_paypal_order'),
    path('pagos/paypal/<int:reserva_id>/capture/', views.capture_paypal_order, name='capture_paypal_order'),
    path('webhooks/lemonsqueezy/', views.lemonsqueezy_webhook, name='lemonsqueezy_webhook'),
    path('webhooks/paypal/', views.paypal_webhook, name='paypal_webhook'),

    path('galeria/', views.galeria_view, name='galeria'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
